#pragma once

#define PASSWORD_MAKER_VERSION_MAJOR	0
#define PASSWORD_MAKER_VERSION_MINOR	0
#define PASSWORD_MAKER_VERSION_PATCH	3
#define PASSWORD_MAKER_VERSION			"0.0.3"

#define CMAKE_COMPILER					"MSVC"
#define CMAKE_COMPILER_VERSION			"19.25.28614.0"
#define CMAKE_VERSION					"3.17.1"
#define CMAKE_COMPILE_DATE				"2020-04-21"
#define CMAKE_SYSTEM					"Windows"
#define CMAKE_SYSTEM_VERSION			"10.0.18363"
